.read sp16data.sql
.read fa16data.sql

CREATE TABLE obedience AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE smallest_int AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE greatstudents AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE sevens AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE matchmaker AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";
