.read lab12.sql

CREATE TABLE sp16favnum AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp16favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE fa16favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE fa16dragon AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE fa16alldragons AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE obedienceimage AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE smallest_int_count AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";
