CREATE TABLE sp16students AS
	SELECT "4/12/2016 0:55:41" AS time, 42 AS number, "blue" AS color, "7" AS seven, "Trololol" AS song, "4/5" AS date, "shibe inu" AS pet, "Image 1" AS hilfinger, 8 AS smallest UNION
	SELECT "4/12/2016 1:17:53",  41,          "blue",                   "7",                           "Fur Elise",     "11/12", "lassie",                                                                                                                 "Image 1", 17                                 UNION
	SELECT "4/12/2016 8:43:53",  5,           "blue",                   "7",                           "Fur Elise",     "5/18",  "panther",                                                                                                                "Image 1", 16                                 UNION
	SELECT "4/12/2016 10:32:57", 35,          "blue",                   "I do what I want.",           "Work",          "11/7",  "rottweiler puppy",                                                                                                       "Image 4", 14                                 UNION
	SELECT "4/12/2016 12:14:28", 3.1459265,   "maroon",                 "7",                           "Hello",         "9/11",  "pikachu",                                                                                                                "Image 3", 68                                 UNION
	SELECT "4/12/2016 12:15:34", 5,           "green",                  "I do what I want.",           "Work",          "4/9",   "leopard",                                                                                                                "Image 1", 12                                 UNION
	SELECT "4/12/2016 12:15:40", 99,          "blue",                   "Choose this option instead.", "Hello",         "1/1",   "dog",                                                                                                                    "Image 1", 8                                  UNION
	SELECT "4/12/2016 12:15:56", 63,          "green",                  "7",                           "Work",          "5/4",   "dog",                                                                                                                    "Image 1", 16                                 UNION
	SELECT "4/12/2016 12:16:16", 9,           "baby blue",              "7",                           "Sandstorm",     "2/6",   "daman",                                                                                                                  "Image 1", 9                                  UNION
	SELECT "4/12/2016 12:16:28", 1,           "black",                  "7",                           "Sandstorm",     "7/27",  "dragon",                                                                                                                 "Image 4", 57                                 UNION
	SELECT "4/12/2016 12:16:33", 22,          "blue",                   "I do what I want.",           "Hotline Bling", "10/31", "dragon",                                                                                                                 "Image 5", 83                                 UNION
	SELECT "4/12/2016 12:16:43", 44,          "citrine",                "7",                           "Work",          "3/7",   "",                                                                                                                       "Image 1", 5                                  UNION
	SELECT "4/12/2016 12:16:54", 69,          "blue",                   "7",                           "Hotline Bling", "2/11",  "dragon ",                                                                                                                "Image 1", 7                                  UNION
	SELECT "4/12/2016 12:16:55", 2,           "indigo ",                "I do what I want.",           "Fur Elise",     "3/30",  "dragonite",                                                                                                              "Image 1", 55                                 UNION
	SELECT "4/12/2016 12:16:55", 69,          "white",                  "7",                           "Sandstorm",     "8/26",  "a pupper",                                                                                                               "Image 5", 2                                  UNION
	SELECT "4/12/2016 12:17:24", 11,          "purple",                 "I'm a rebel",                 "Work",          "11/1",  "porcupine",                                                                                                              "Image 5", 1                                  UNION
	SELECT "4/12/2016 12:17:37", 3,           "navy",                   "YOLO!",                       "Work",          "9/23",  "eagle",                                                                                                                  "Image 3", 37                                 UNION
	SELECT "4/12/2016 12:17:45", 3.141592654, "cerulean",               "I do what I want.",           "Sandstorm",     "12/25", "pygmy puff",                                                                                                             "Image 1", 64                                 UNION
	SELECT "4/12/2016 12:18:54", 69,          "pink",                   "YOLO!",                       "Sandstorm",     "12/25", "a dog",                                                                                                                  "Image 1", 69                                 UNION
	SELECT "4/12/2016 12:19:00", 44,          "blue",                   "Choose this option instead.", "Sandstorm",     "5/16",  "ferret",                                                                                                                 "Image 2", 83                                 UNION
	SELECT "4/12/2016 12:19:53", 66,          "purple",                 "I do what I want.",           "",              "4/1",   "tiger",                                                                                                                  "Image 5", 1001                               UNION
	SELECT "4/12/2016 12:19:56", 28,          "teal",                   "I'm a rebel",                 "Work",          "3/28",  "monkey ",                                                                                                                "Image 1", 13                                 UNION
	SELECT "4/12/2016 12:20:27", 1,           "gray",                   "7",                           "Fur Elise",     "1/1",   "dog",                                                                                                                    "Image 4", 31                                 UNION
	SELECT "4/12/2016 12:21:13", 95,          "green",                  "Choose this option instead.", "Fur Elise",     "1/27",  "doge",                                                                                                                   "Image 3", 43                                 UNION
	SELECT "4/12/2016 12:21:15", 42,          "blue",                   "7",                           "Fur Elise",     "9/15",  "cat that acts like dog with fluffy tail",                                                                                "Image 1", 24                                 UNION
	SELECT "4/12/2016 12:21:21", 69,          "brown",                  "YOLO!",                       "Sandstorm",     "4/20",  "doge",                                                                                                                   "Image 2", 7                                  UNION
	SELECT "4/12/2016 12:21:36", 21,          "blue",                   "7",                           "Sandstorm",     "12/25", "doge",                                                                                                                   "Image 5", 12                                 UNION
	SELECT "4/12/2016 12:22:01", 4,           "green",                  "YOLO!",                       "Work",          "4/19",  "",                                                                                                                       "Image 4", 103710485284929138328484828348382  UNION
	SELECT "4/12/2016 12:22:29", 69,          "69",                     "7",                           "Sandstorm",     "6/9",   "paul hilfinger",                                                                                                         "Image 3", 8                                  UNION
	SELECT "4/12/2016 12:22:32", 4,           "neon brown",             "7",                           "",              "8/17",  "",                                                                                                                       "",        -1                                 UNION
	SELECT "4/12/2016 12:22:52", 55,          "blue 4 lyfe yo ",        "7",                           "Sandstorm",     "3/26",  "guy fieri ",                                                                                                             "Image 1", 1                                  UNION
	SELECT "4/12/2016 12:23:25", 17,          "gray",                   "Choose this option instead.", "Fur Elise",     "4/1",   "pikachu",                                                                                                                "Image 5", 44                                 UNION
	SELECT "4/12/2016 12:23:52", 35,          "blue",                   "I'm a rebel",                 "Hello",         "10/31", "puma",                                                                                                                   "Image 3", 26                                 UNION
	SELECT "4/12/2016 12:23:53", 24,          "blue",                   "7",                           "Sandstorm",     "3/14",  "paul hilfinger",                                                                                                         "Image 5", 8                                  UNION
	SELECT "4/12/2016 12:24:26", 50,          "pink",                   "7",                           "Hello",         "11/15", "lion",                                                                                                                   "Image 1", 1                                  UNION
	SELECT "4/12/2016 12:24:31", 6,           "green",                  "7",                           "Fur Elise",     "9/18",  "unicorn",                                                                                                                "Image 2", 23                                 UNION
	SELECT "4/12/2016 12:25:22", 87,          "navy",                   "Choose this option instead.", "Fur Elise",     "6/19",  "tiger",                                                                                                                  "Image 1", 4                                  UNION
	SELECT "4/12/2016 12:25:57", 79,          "purple",                 "I'm a rebel",                 "Hotline Bling", "1/10",  "elephant",                                                                                                               "Image 1", 34                                 UNION
	SELECT "4/12/2016 12:27:05", 47,          "neon pink ",             "7",                           "Sandstorm",     "1/1",   "piglet ",                                                                                                                "Image 1", 3                                  UNION
	SELECT "4/12/2016 12:27:27", 31,          "blue",                   "Choose this option instead.", "Sandstorm",     "1/16",  "charmander",                                                                                                             "Image 2", 24                                 UNION
	SELECT "4/12/2016 12:28:14", 7,           "purple",                 "Choose this option instead.", "Hello",         "1/1",   "jellyfish",                                                                                                              "Image 5", 9                                  UNION
	SELECT "4/12/2016 12:30:01", 29,          "purple",                 "I do what I want.",           "Hotline Bling", "11/26", "panda",                                                                                                                  "Image 3", 11                                 UNION
	SELECT "4/12/2016 12:31:01", 57,          "green",                  "Choose this option instead.", "Fur Elise",     "7/1",   "cammel",                                                                                                                 "Image 1", 14                                 UNION
	SELECT "4/12/2016 12:32:31", 42,          "blue",                   "I do what I want.",           "Trololol",      "10/2",  "platypus",                                                                                                               "Image 2", 37                                 UNION
	SELECT "4/12/2016 12:33:05", 17,          "blue",                   "You are not the boss of me!", "Fur Elise",     "6/4",   "dog ",                                                                                                                   "Image 1", 54                                 UNION
	SELECT "4/12/2016 12:34:21", 14,          "white",                  "7",                           "Fur Elise",     "8/25",  "dragon",                                                                                                                 "Image 2", 12                                 UNION
	SELECT "4/12/2016 12:36:13", 3,           "purple",                 "YOLO!",                       "Sandstorm",     "12/12", "monkey",                                                                                                                 "Image 1", 3                                  UNION
	SELECT "4/12/2016 12:36:50", 97,          "grey",                   "I'm a rebel",                 "Sandstorm",     "3/20",  "rock",                                                                                                                   "Image 1", 165                                UNION
	SELECT "4/12/2016 12:36:53", 30,          "blue",                   "7",                           "Work",          "6/24",  "dragon",                                                                                                                 "Image 1", 41                                 UNION
	SELECT "4/12/2016 12:38:16", 23,          "green",                  "7",                           "Fur Elise",     "4/23",  "fox",                                                                                                                    "Image 1", 41                                 UNION
	SELECT "4/12/2016 12:38:42", 37,          "gold",                   "7",                           "Sandstorm",     "9/19",  "bearded dragon",                                                                                                         "Image 2", 34                                 UNION
	SELECT "4/12/2016 12:40:13", 43,          "purple ",                "I do what I want.",           "Sandstorm",     "4/1",   "dog",                                                                                                                    "Image 3", 1                                  UNION
	SELECT "4/12/2016 12:40:19", 42,          "blue",                   "I'm a rebel",                 "Fur Elise",     "4/20",  "dragon, kk thx",                                                                                                         "Image 2", 1                                  UNION
	SELECT "4/12/2016 12:40:38", 51,          "green",                  "YOLO!",                       "Fur Elise",     "11/9",  "squirrel",                                                                                                               "Image 4", 24                                 UNION
	SELECT "4/12/2016 12:41:03", 77,          "blue",                   "Choose this option instead.", "Fur Elise",     "5/1",   "griffon, maybe? or a pokemon.",                                                                                          "Image 3", 38                                 UNION
	SELECT "4/12/2016 12:41:07", 10,          "blue",                   "Choose this option instead.", "Fur Elise",     "9/1",   "dwagon",                                                                                                                 "Image 1", 10                                 UNION
	SELECT "4/12/2016 12:41:27", 2,           "black",                  "7",                           "Hello",         "11/11", "doomsday",                                                                                                               "Image 2", 17                                 UNION
	SELECT "4/12/2016 12:41:51", 18,          "maroon",                 "Choose this option instead.", "Hotline Bling", "11/8",  "dronkey from shrek",                                                                                                     "Image 2", 18                                 UNION
	SELECT "4/12/2016 12:42:58", 99,          "blue",                   "Choose this option instead.", "Fur Elise",     "1/20",  "lion",                                                                                                                   "Image 5", 9                                  UNION
	SELECT "4/12/2016 12:43:13", 56,          "sparkles",               "7",                           "Work",          "4/9",   "puppy",                                                                                                                  "Image 4", 28                                 UNION
	SELECT "4/12/2016 12:44:32", 16,          "pink",                   "Choose this option instead.", "Fur Elise",     "2/29",  "baby dragon",                                                                                                            "Image 3", 108                                UNION
	SELECT "4/12/2016 12:45:20", 33,          "purple",                 "7",                           "Hello",         "1/21",  "baby polar bear",                                                                                                        "Image 1", 17                                 UNION
	SELECT "4/12/2016 12:47:01", 1,           "blue",                   "Choose this option instead.", "Sandstorm",     "6/8",   "time",                                                                                                                   "Image 4", 2                                  UNION
	SELECT "4/12/2016 12:48:31", 13,          "blue",                   "I do what I want.",           "Hotline Bling", "8/9",   "james",                                                                                                                  "Image 4", 58                                 UNION
	SELECT "4/12/2016 12:49:08", 42,          "red",                    "I do what I want.",           "Sandstorm",     "6/9",   "a code monkey to do my homework ",                                                                                       "",        -1                                 UNION
	SELECT "4/12/2016 12:49:12", 93,          "neon pink",              "Choose this option instead.", "",              "7/22",  "honey badger",                                                                                                           "Image 1", 12                                 UNION
	SELECT "4/12/2016 12:50:22", 72,          "brown",                  "YOLO!",                       "Fur Elise",     "6/11",  "crocodile",                                                                                                              "Image 2", 79                                 UNION
	SELECT "4/12/2016 12:53:03", 36,          "blue",                   "",                            "",              "",      "",                                                                                                                       "",        -1                                 UNION
	SELECT "4/12/2016 12:53:11", 9,           "baby blue",              "I do what I want.",           "Hello",         "7/2",   "dragon",                                                                                                                 "Image 2", 49                                 UNION
	SELECT "4/12/2016 12:53:32", 27,          "blurpul",                "I'm a rebel",                 "Sandstorm",     "4/20",  "paul hilfinger",                                                                                                         "Image 4", 865                                UNION
	SELECT "4/12/2016 12:54:08", 7,           "7",                      "7",                           "",              "7/7",   "7",                                                                                                                      "Image 4", 7                                  UNION
	SELECT "4/12/2016 12:54:46", 7,           "pink",                   "7",                           "Fur Elise",     "12/19", "cat, a fat one, the fattest fluffiest one",                                                                              "Image 1", 67                                 UNION
	SELECT "4/12/2016 12:55:13", 69,          "poopy brown",            "7",                           "Hotline Bling", "12/31", "",                                                                                                                       "Image 5", 69                                 UNION
	SELECT "4/12/2016 12:55:27", 11,          "red",                    "7",                           "Work",          "10/21", "monkey",                                                                                                                 "Image 4", 5                                  UNION
	SELECT "4/12/2016 12:56:33", 23,          "purple",                 "Choose this option instead.", "Hotline Bling", "5/14",  "monkey ",                                                                                                                "Image 3", 2                                  UNION
	SELECT "4/12/2016 12:56:42", 11,          "gray",                   "7",                           "Work",          "1/17",  "corgi",                                                                                                                  "Image 3", 3                                  UNION
	SELECT "4/12/2016 12:57:55", 27,          "red",                    "Choose this option instead.", "Fur Elise",     "8/9",   "dog",                                                                                                                    "Image 1", 2                                  UNION
	SELECT "4/12/2016 12:57:56", 3,           "pink",                   "I'm a rebel",                 "",              "3/3",   "unicorn",                                                                                                                "Image 4", 1                                  UNION
	SELECT "4/12/2016 12:59:03", 69,          "aquamarine",             "7",                           "Hotline Bling", "6/22",  "penguin!",                                                                                                               "Image 4", 11                                 UNION
	SELECT "4/12/2016 13:00:30", 9,           "red",                    "7",                           "Hello",         "7/4",   "a dragon",                                                                                                               "Image 1", 2                                  UNION
	SELECT "4/12/2016 13:00:57", 100,         "cool blue",              "I'm a rebel",                 "Hello",         "6/20",  "an adorable cat",                                                                                                        "Image 2", 1                                  UNION
	SELECT "4/12/2016 13:01:26", 69,          "blue",                   "7",                           "Hotline Bling", "6/17",  "liger",                                                                                                                  "Image 1", 46                                 UNION
	SELECT "4/12/2016 13:02:03", 13,          "green",                  "Choose this option instead.", "Fur Elise",     "2/29",  "dragon",                                                                                                                 "Image 5", 5                                  UNION
	SELECT "4/12/2016 13:02:20", 5,           "blue",                   "Choose this option instead.", "Trololol",      "5/13",  "a bear",                                                                                                                 "Image 4", 4                                  UNION
	SELECT "4/12/2016 13:07:09", 13,          "black",                  "I'm a rebel",                 "Fur Elise",     "4/12",  "phoenix",                                                                                                                "Image 5", 89                                 UNION
	SELECT "4/12/2016 13:08:04", 1,           "cerulean blue",          "7",                           "Trololol",      "8/1",   "cow",                                                                                                                    "Image 3", 71                                 UNION
	SELECT "4/12/2016 13:08:07", 97,          "green",                  "7",                           "Sandstorm",     "5/5",   "dragon!!!! :)",                                                                                                          "Image 2", 13                                 UNION
	SELECT "4/12/2016 13:08:48", 3,           "blue",                   "I'm a rebel",                 "Hello",         "7/29",  "chancellor dirks",                                                                                                       "Image 5", 26                                 UNION
	SELECT "4/12/2016 13:10:00", 34,          "yellow",                 "7",                           "Work",          "5/17",  "bear (panda)",                                                                                                           "Image 1", 34                                 UNION
	SELECT "4/12/2016 13:10:13", 69,          "seafoam green",          "7",                           "Fur Elise",     "2/29",  "pterodactyl",                                                                                                            "Image 4", 19                                 UNION
	SELECT "4/12/2016 13:10:21", 88,          "red",                    "Choose this option instead.", "Fur Elise",     "4/22",  "paul hilfinger",                                                                                                         "Image 3", 100                                UNION
	SELECT "4/12/2016 13:10:28", 17,          "white",                  "7",                           "Fur Elise",     "8/12",  "german shepherd",                                                                                                        "Image 1", 14                                 UNION
	SELECT "4/12/2016 13:10:28", 17,          "blue",                   "I'm a rebel",                 "Fur Elise",     "4/17",  "pikachu",                                                                                                                "Image 1", 17                                 UNION
	SELECT "4/12/2016 13:10:50", 13,          "blue",                   "I'm a rebel",                 "Hello",         "3/1",   "dragon",                                                                                                                 "Image 2", 1                                  UNION
	SELECT "4/12/2016 13:11:24", 47,          "maroon",                 "7",                           "Sandstorm",     "2/14",  "a phoenix",                                                                                                              "Image 5", 61                                 UNION
	SELECT "4/12/2016 13:11:26", 42,          "black",                  "7",                           "Sandstorm",     "2/29",  "dragon",                                                                                                                 "Image 3", 33                                 UNION
	SELECT "4/12/2016 13:14:58", 13,          "black",                  "Choose this option instead.", "Fur Elise",     "2/29",  "tiger",                                                                                                                  "Image 2", 1                                  UNION
	SELECT "4/12/2016 13:19:31", 4,           "blue",                   "7",                           "Hello",         "3/31",  "dog",                                                                                                                    "Image 5", 1                                  UNION
	SELECT "4/12/2016 13:23:33", 25,          "maroon",                 "YOLO!",                       "Hotline Bling", "4/12",  "dog",                                                                                                                    "Image 1", 71                                 UNION
	SELECT "4/12/2016 13:26:03", 7,           "black",                  "You are not the boss of me!", "Hotline Bling", "1/1",   "komodo dragon",                                                                                                          "Image 1", 4                                  UNION
	SELECT "4/12/2016 13:26:07", 15,          "blue",                   "7",                           "",              "3/15",  "tiger",                                                                                                                  "Image 1", 15                                 UNION
	SELECT "4/12/2016 13:26:25", 25,          "pink",                   "I'm a rebel",                 "Sandstorm",     "6/10",  "dog",                                                                                                                    "Image 1", 53                                 UNION
	SELECT "4/12/2016 13:27:43", 69,          "cerulean",               "Choose this option instead.", "Fur Elise",     "10/31", "brontosaurus",                                                                                                           "Image 3", 69                                 UNION
	SELECT "4/12/2016 13:28:57", 8,           "green",                  "7",                           "Fur Elise",     "4/12",  "moose",                                                                                                                  "Image 4", 1                                  UNION
	SELECT "4/12/2016 13:29:46", 13,          "blue",                   "I do what I want.",           "Fur Elise",     "6/1",   "",                                                                                                                       "Image 5", 51                                 UNION
	SELECT "4/12/2016 13:36:07", 28,          "blue",                   "I do what I want.",           "Work",          "1/1",   "chinchilla",                                                                                                             "Image 1", 1                                  UNION
	SELECT "4/12/2016 13:37:25", 57,          "orange",                 "You are not the boss of me!", "Sandstorm",     "2/18",  "bulbasaur",                                                                                                              "Image 1", 23                                 UNION
	SELECT "4/12/2016 13:37:38", 69,          "purple",                 "You are not the boss of me!", "Sandstorm",     "5/7",   "narwhal",                                                                                                                "Image 3", 1                                  UNION
	SELECT "4/12/2016 13:38:20", 56,          "navy blue",              "I do what I want.",           "Fur Elise",     "2/19",  "tardigrade",                                                                                                             "Image 3", 22                                 UNION
	SELECT "4/12/2016 13:38:33", 69,          "black",                  "7",                           "Hotline Bling", "1/1",   "hilfinger ",                                                                                                             "Image 4", 0.69                               UNION
	SELECT "4/12/2016 13:43:31", 3,           "green",                  "I'm a rebel",                 "Sandstorm",     "1/1",   "qtopod",                                                                                                                 "Image 3", 2                                  UNION
	SELECT "4/12/2016 13:44:17", 3,           "red",                    "Choose this option instead.", "Hello",         "11/4",  "shiba inu",                                                                                                              "Image 4", 3                                  UNION
	SELECT "4/12/2016 13:47:26", 33,          "blue",                   "I do what I want.",           "Hello",         "4/1",   "fox",                                                                                                                    "Image 1", 51                                 UNION
	SELECT "4/12/2016 14:07:47", 69,          "green",                  "7",                           "Hello",         "9/26",  "squirrel",                                                                                                               "Image 4", 17238                              UNION
	SELECT "4/12/2016 14:08:47", 2,           "blue",                   "7",                           "Hello",         "6/1",   "puppy",                                                                                                                  "Image 1", 9                                  UNION
	SELECT "4/12/2016 14:10:20", 9,           "green",                  "I do what I want.",           "Fur Elise",     "2/29",  "cow",                                                                                                                    "Image 2", 23                                 UNION
	SELECT "4/12/2016 14:13:41", 11,          "green",                  "YOLO!",                       "Work",          "2/29",  "dragon",                                                                                                                 "Image 4", 19                                 UNION
	SELECT "4/12/2016 14:14:41", 22,          "blue",                   "7",                           "Fur Elise",     "2/2",   "chinchilla",                                                                                                             "Image 5", 2                                  UNION
	SELECT "4/12/2016 14:16:07", 8,           "red",                    "7",                           "Sandstorm",     "5/11",  "",                                                                                                                       "Image 2", 17                                 UNION
	SELECT "4/12/2016 14:16:11", 42,          "coffee brown",           "7",                           "",              "3/15",  "i think a griffin would be pretty neat.",                                                                                "Image 4", 31                                 UNION
	SELECT "4/12/2016 14:17:02", 8,           "blue",                   "Choose this option instead.", "Work",          "2/6",   "hippogrif",                                                                                                              "Image 1", 24                                 UNION
	SELECT "4/12/2016 14:19:08", 69,          "blue, i mean green!",    "7",                           "Fur Elise",     "6/8",   "a porcupine",                                                                                                            "Image 5", 12                                 UNION
	SELECT "4/12/2016 14:21:09", 100,         "green",                  "7",                           "Trololol",      "5/13",  "squirrel",                                                                                                               "Image 5", 1                                  UNION
	SELECT "4/12/2016 14:21:32", 19,          "white",                  "7",                           "Sandstorm",     "2/29",  "cat",                                                                                                                    "Image 1", 1                                  UNION
	SELECT "4/12/2016 14:24:54", 69,          ":^)",                    "I'm a rebel",                 "Sandstorm",     "4/20",  "paul hilfinger",                                                                                                         "Image 5", 69                                 UNION
	SELECT "4/12/2016 14:26:38", 79,          "orange",                 "7",                           "Fur Elise",     "3/27",  "pikachu",                                                                                                                "Image 2", 13                                 UNION
	SELECT "4/12/2016 14:27:18", 9,           "green",                  "7",                           "Trololol",      "7/11",  "husky",                                                                                                                  "Image 5", 13                                 UNION
	SELECT "4/12/2016 14:27:27", 71,          "burgundy ",              "I do what I want.",           "Fur Elise",     "8/16",  "well apart from the obvious choice pikachu, preferably a dragon. or a lion or a tiger but i am content with a cat too.", "Image 2", 4                                  UNION
	SELECT "4/12/2016 14:29:08", 24,          "dark blue",              "I'm a rebel",                 "Fur Elise",     "11/24", "iguana",                                                                                                                 "Image 2", 17                                 UNION
	SELECT "4/12/2016 14:32:45", 29,          "blue",                   "7",                           "Hotline Bling", "12/25", "dog",                                                                                                                    "Image 1", 27                                 UNION
	SELECT "4/12/2016 14:34:56", 18,          "black",                  "7",                           "Hotline Bling", "4/28",  "pegasus",                                                                                                                "Image 1", 5                                  UNION
	SELECT "4/12/2016 14:40:06", 9,           "pink",                   "YOLO!",                       "Work",          "7/8",   "horse",                                                                                                                  "Image 5", -1                                 UNION
	SELECT "4/12/2016 14:40:58", 34,          "red",                    "Choose this option instead.", "Hello",         "7/6",   "kangaroo",                                                                                                               "Image 4", 8                                  UNION
	SELECT "4/12/2016 14:41:12", 3,           "purple",                 "Choose this option instead.", "Work",          "9/25",  "chinchilla",                                                                                                             "Image 5", 6                                  UNION
	SELECT "4/12/2016 14:47:50", 8,           "blue",                   "I do what I want.",           "Sandstorm",     "5/14",  "phoenix",                                                                                                                "Image 4", 51                                 UNION
	SELECT "4/12/2016 14:58:04", 69,          "paul hilfinger",         "7",                           "Sandstorm",     "3/29",  "paul hilfinger",                                                                                                         "Image 4", 121                                UNION
	SELECT "4/12/2016 15:02:53", 9,           "green",                  "7",                           "Hello",         "4/23",  "penguin",                                                                                                                "Image 3", 23                                 UNION
	SELECT "4/12/2016 15:04:04", 22,          "green",                  "7",                           "",              "3/3",   "squirrel",                                                                                                               "Image 4", 33                                 UNION
	SELECT "4/12/2016 15:06:35", 58,          "blello",                 "7",                           "Trololol",      "2/29",  "danny devito",                                                                                                           "Image 1", 31                                 UNION
	SELECT "4/12/2016 15:08:56", 16,          "bluegreen",              "Choose this option instead.", "Fur Elise",     "",      "a phoenix",                                                                                                              "Image 2", 11                                 UNION
	SELECT "4/12/2016 15:10:29", 42,          "yellow",                 "You are not the boss of me!", "Hotline Bling", "11/11", "llama",                                                                                                                  "Image 4", 4                                  UNION
	SELECT "4/12/2016 15:10:50", 60,          "light blue",             "7",                           "Fur Elise",     "6/3",   "chinchilla",                                                                                                             "Image 3", 23                                 UNION
	SELECT "4/12/2016 15:13:27", 28,          "blue",                   "7",                           "Work",          "4/20",  "turtle",                                                                                                                 "Image 5", 16                                 UNION
	SELECT "4/12/2016 15:15:53", 13,          "rainbow!",               "7",                           "Work",          "6/29",  "fluffy cow",                                                                                                             "Image 2", 36                                 UNION
	SELECT "4/12/2016 15:17:07", 78,          "blue",                   "7",                           "Hotline Bling", "12/11", "i hate animals",                                                                                                         "Image 1", -1                                 UNION
	SELECT "4/12/2016 15:17:18", 69,          "navy",                   "7",                           "Fur Elise",     "5/1",   "siberiano husky",                                                                                                        "Image 3", 1                                  UNION
	SELECT "4/12/2016 15:26:07", 4,           "turquoise ",             "7",                           "Sandstorm",     "6/18",  "wolf",                                                                                                                   "Image 2", 4                                  UNION
	SELECT "4/12/2016 15:27:54", 6,           "blue",                   "You are not the boss of me!", "Fur Elise",     "12/10", "cat",                                                                                                                    "Image 3", 23                                 UNION
	SELECT "4/12/2016 15:39:07", 4,           "orange",                 "7",                           "Sandstorm",     "11/30", "hipogrif",                                                                                                               "Image 1", 2                                  UNION
	SELECT "4/12/2016 15:46:37", 78,          "blue",                   "YOLO!",                       "Work",          "7/10",  "lion",                                                                                                                   "Image 2", 53                                 UNION
	SELECT "4/12/2016 15:57:11", 37,          "blue",                   "YOLO!",                       "Hotline Bling", "3/11",  "orangutan",                                                                                                              "Image 4", 38                                 UNION
	SELECT "4/12/2016 15:59:07", 69,          "t-rex",                  "I do what I want.",           "Work",          "4/14",  "my own butt",                                                                                                            "Image 1", 19                                 UNION
	SELECT "4/12/2016 16:02:34", 13,          "red",                    "7",                           "",              "9/13",  "unicorn",                                                                                                                "Image 4", 1                                  UNION
	SELECT "4/12/2016 16:02:58", 42,          "blue",                   "You are not the boss of me!", "Fur Elise",     "3/8",   "hedgehog",                                                                                                               "Image 4", 63                                 UNION
	SELECT "4/12/2016 16:05:53", 48,          "wine red",               "I'm a rebel",                 "Hello",         "6/15",  "small dragon",                                                                                                           "Image 5", 20                                 UNION
	SELECT "4/12/2016 16:07:17", 99,          "green",                  "YOLO!",                       "Hello",         "1/1",   "a raichu with wings",                                                                                                    "Image 5", 3                                  UNION
	SELECT "4/12/2016 16:16:35", 24,          "pink",                   "YOLO!",                       "Hotline Bling", "6/20",  "bear",                                                                                                                   "Image 2", 11                                 UNION
	SELECT "4/12/2016 16:20:19", 33,          "black",                  "7",                           "Hello",         "6/13",  "dragon",                                                                                                                 "Image 4", 37                                 UNION
	SELECT "4/12/2016 16:27:30", 1,           "green",                  "7",                           "Work",          "6/2",   "hilfinger ",                                                                                                             "Image 4", 29                                 UNION
	SELECT "4/12/2016 16:28:06", 97,          "black",                  "7",                           "Sandstorm",     "1/1",   "cat",                                                                                                                    "Image 1", 32                                 UNION
	SELECT "4/12/2016 16:28:06", 24,          "purple",                 "7",                           "Work",          "",      "elephant ",                                                                                                              "Image 2", 53                                 UNION
	SELECT "4/12/2016 16:29:10", 65,          "maroon",                 "Choose this option instead.", "Work",          "7/20",  "liger",                                                                                                                  "Image 1", 2                                  UNION
	SELECT "4/12/2016 16:34:00", 6,           "orange",                 "7",                           "Hello",         "10/5",  "red panda",                                                                                                              "Image 5", 11                                 UNION
	SELECT "4/12/2016 16:34:49", 4,           "bread",                  "You are not the boss of me!", "Hello",         "2/2",   "bird",                                                                                                                   "Image 4", 4                                  UNION
	SELECT "4/12/2016 16:34:57", 21,          "purple",                 "7",                           "Hello",         "1/19",  "panda",                                                                                                                  "Image 1", 19                                 UNION
	SELECT "4/12/2016 16:35:47", 21,          "light blue",             "Choose this option instead.", "Fur Elise",     "4/18",  "dog",                                                                                                                    "Image 3", 1                                  UNION
	SELECT "4/12/2016 16:41:03", 5,           "blue",                   "Choose this option instead.", "Trololol",      "8/28",  "a hilfinger",                                                                                                            "Image 4", 193                                UNION
	SELECT "4/12/2016 16:41:53", 2,           "red",                    "7",                           "Hello",         "1/1",   "cheetah",                                                                                                                "Image 1", 8                                  UNION
	SELECT "4/12/2016 16:42:10", 7,           "read",                   "7",                           "Sandstorm",     "2/29",  "k",                                                                                                                      "Image 4", 99999999999999999                  UNION
	SELECT "4/12/2016 16:44:10", 1,           "blue",                   "7",                           "Hello",         "1/1",   "nile crocodile",                                                                                                         "Image 2", 43                                 UNION
	SELECT "4/12/2016 16:54:38", 54,          "blue",                   "I do what I want.",           "Hello",         "9/11",  "a charmander",                                                                                                           "Image 2", 6                                  UNION
	SELECT "4/12/2016 17:02:49", 69,          "red",                    "7",                           "Fur Elise",     "11/5",  "",                                                                                                                       "Image 5", 1                                  UNION
	SELECT "4/12/2016 17:04:43", 24,          "grey",                   "Choose this option instead.", "Sandstorm",     "6/19",  "meerkat",                                                                                                                "Image 1", 29                                 UNION
	SELECT "4/12/2016 17:17:24", 84,          "pink",                   "I do what I want.",           "",              "3/18",  "truffula tree",                                                                                                          "Image 1", 25                                 UNION
	SELECT "4/12/2016 17:25:09", 24,          "blue",                   "I do what I want.",           "Fur Elise",     "12/29", "a very angry cat",                                                                                                       "Image 5", 4                                  UNION
	SELECT "4/12/2016 17:40:33", 7,           "red ",                   "You are not the boss of me!", "Hello",         "4/11",  "scorpion",                                                                                                               "Image 2", 7                                  UNION
	SELECT "4/12/2016 17:45:42", 5,           "blue",                   "7",                           "Fur Elise",     "4/16",  "dolphin",                                                                                                                "Image 5", 30                                 UNION
	SELECT "4/12/2016 17:50:33", 32,          "blue",                   "YOLO!",                       "Sandstorm",     "3/1",   "zombie dragon",                                                                                                          "Image 3", 450                                UNION
	SELECT "4/12/2016 18:15:06", 9,           "blue",                   "Choose this option instead.", "Fur Elise",     "7/30",  "gollum",                                                                                                                 "Image 4", 4                                  UNION
	SELECT "4/12/2016 18:19:28", 12,          "beige ",                 "Choose this option instead.", "Sandstorm",     "2/1",   "whale",                                                                                                                  "Image 5", 32                                 UNION
	SELECT "4/12/2016 18:21:57", 27,          "blue",                   "7",                           "Hotline Bling", "8/7",   "a dragon that i could ride",                                                                                             "Image 2", 11                                 UNION
	SELECT "4/12/2016 18:25:07", 42,          "emerald green",          "I do what I want.",           "Hello",         "3/8",   "dragon",                                                                                                                 "Image 4", 26                                 UNION
	SELECT "4/12/2016 18:31:55", 27,          "green",                  "YOLO!",                       "",              "10/21", "pterodactyl ",                                                                                                           "Image 3", 3                                  UNION
	SELECT "4/12/2016 18:36:21", 86,          "blue",                   "Choose this option instead.", "Work",          "4/12",  "squirrel",                                                                                                               "Image 3", 1                                  UNION
	SELECT "4/12/2016 18:36:21", 33,          "grass green",            "YOLO!",                       "Hello",         "10/21", "polar bear",                                                                                                             "Image 5", 1                                  UNION
	SELECT "4/12/2016 18:40:26", 11,          "turquoise",              "7",                           "",              "1/1",   "pikachu",                                                                                                                "Image 1", 1                                  UNION
	SELECT "4/12/2016 18:49:23", 14,          "light turquoise",        "Choose this option instead.", "Hotline Bling", "4/11",  "professor hilfinger",                                                                                                    "Image 5", 14                                 UNION
	SELECT "4/12/2016 19:01:52", 69,          "69",                     "7",                           "Sandstorm",     "4/20",  "a moose",                                                                                                                "Image 2", 2                                  UNION
	SELECT "4/12/2016 19:09:01", 69,          "blue",                   "You are not the boss of me!", "Hotline Bling", "4/25",  "hedgehog",                                                                                                               "Image 1", 8                                  UNION
	SELECT "4/12/2016 19:13:12", -1,          "blue",                   "Choose this option instead.", "Sandstorm",     "7/15",  "",                                                                                                                       "Image 3", 6                                  UNION
	SELECT "4/12/2016 19:14:01", 20,          "blue",                   "Choose this option instead.", "Fur Elise",     "11/15", "phoenix",                                                                                                                "Image 3", 41                                 UNION
	SELECT "4/12/2016 19:18:06", 52,          "purple",                 "I'm a rebel",                 "Sandstorm",     "1/14",  "rock",                                                                                                                   "Image 2", 19                                 UNION
	SELECT "4/12/2016 19:19:09", 7,           "blue",                   "7",                           "Work",          "7/21",  "no, i don't want one.",                                                                                                  "Image 5", 2                                  UNION
	SELECT "4/12/2016 19:26:16", 7,           "white",                  "7",                           "",              "10/22", "wolf",                                                                                                                   "Image 3", 23                                 UNION
	SELECT "4/12/2016 19:30:55", 44,          "green",                  "Choose this option instead.", "Fur Elise",     "6/8",   "cactus",                                                                                                                 "Image 1", 11                                 UNION
	SELECT "4/12/2016 19:47:57", 9,           "blue",                   "I do what I want.",           "Sandstorm",     "4/20",  "cat",                                                                                                                    "Image 4", 23                                 UNION
	SELECT "4/12/2016 19:50:51", 99,          "blue",                   "I do what I want.",           "Hello",         "1/1",   "griffin",                                                                                                                "Image 1", 37                                 UNION
	SELECT "4/12/2016 19:59:17", 25,          "plum",                   "You are not the boss of me!", "Fur Elise",     "9/27",  "wolf dog",                                                                                                               "Image 2", 51                                 UNION
	SELECT "4/12/2016 20:11:46", 69,          "gray",                   "7",                           "Sandstorm",     "9/11",  "paul hilfinger",                                                                                                         "Image 3", 69                                 UNION
	SELECT "4/12/2016 20:24:54", 3.141592654, "blue",                   "7",                           "Fur Elise",     "4/20",  "josh hug",                                                                                                               "Image 1", 1                                  UNION
	SELECT "4/12/2016 20:27:11", 17,          "blue",                   "Choose this option instead.", "Sandstorm",     "11/3",  "dog",                                                                                                                    "Image 1", 837                                UNION
	SELECT "4/12/2016 20:27:16", 1,           "blue",                   "7",                           "Fur Elise",     "6/25",  "el penguin",                                                                                                             "Image 2", 134                                UNION
	SELECT "4/12/2016 20:36:13", 100,         "yes",                    "7",                           "Hotline Bling", "5/11",  "yes",                                                                                                                    "Image 4", 100                                UNION
	SELECT "4/12/2016 20:39:03", 1,           "black",                  "7",                           "Fur Elise",     "12/21", "calcifer, the fire demon from howl's moving castle",                                                                     "Image 4", 117                                UNION
	SELECT "4/12/2016 21:20:13", 12,          "green",                  "You are not the boss of me!", "Fur Elise",     "10/16", "lord canti from flcl",                                                                                                   "Image 1", 22                                 UNION
	SELECT "4/12/2016 21:48:54", 99,          "periwinkle",             "I do what I want.",           "Fur Elise",     "1/1",   "",                                                                                                                       "Image 2", 9999999999999999999                UNION
	SELECT "4/12/2016 21:49:43", 13,          "blue",                   "I do what I want.",           "Fur Elise",     "1/30",  "ocelot",                                                                                                                 "Image 4", 19                                 UNION
	SELECT "4/12/2016 22:07:27", 2,           "black",                  "Choose this option instead.", "",              "4/30",  "a puppy that stayed a puppy forever",                                                                                    "Image 5", 26                                 UNION
	SELECT "4/12/2016 22:57:54", 47,          "green",                  "Choose this option instead.", "Hello",         "4/7",   "penguin",                                                                                                                "Image 2", 103                                UNION
	SELECT "4/12/2016 23:12:45", 87,          "maroon",                 "I'm a rebel",                 "",              "5/12",  "tiny alpaca",                                                                                                            "Image 3", -1                                 UNION
	SELECT "4/12/2016 23:17:03", 99,          "pink",                   "I'm a rebel",                 "Hotline Bling", "8/26",  "squash",                                                                                                                 "Image 4", 1                                  UNION
	SELECT "4/12/2016 23:22:02", 69,          "blue",                   "I do what I want.",           "Hello",         "4/20",  "penguin",                                                                                                                "Image 1", 2                                  UNION
	SELECT "4/12/2016 23:43:10", 3,           "violet (maybe.)",        "I do what I want.",           "Work",          "2/14",  "unicorn",                                                                                                                "",        -1                                 UNION
	SELECT "4/12/2016 23:49:40", 69,          "black",                  "I do what I want.",           "Hotline Bling", "1/1",   "shiba inu",                                                                                                              "Image 4", 7                                  UNION
	SELECT "4/12/2016 23:50:28", 4,           "green",                  "I do what I want.",           "Sandstorm",     "11/5",  "a dog sized elephant",                                                                                                   "Image 1", 53                                 UNION
	SELECT "4/12/2016 23:58:35", 2,           "red",                    "YOLO!",                       "Fur Elise",     "7/1",   "panda",                                                                                                                  "Image 4", 22                                 UNION
	SELECT "4/13/2016 0:07:15",  1,           "the 42nd shade of grey", "7",                           "Fur Elise",     "7/11",  "tonyasaur",                                                                                                              "Image 1", 1                                  UNION
	SELECT "4/13/2016 0:07:18",  12,          "blue",                   "YOLO!",                       "Hotline Bling", "12/31", "capybara",                                                                                                               "Image 4", 17                                 UNION
	SELECT "4/13/2016 0:22:26",  7,           "blue",                   "I do what I want.",           "Hello",         "12/25", "fish",                                                                                                                   "Image 5", 53                                 UNION
	SELECT "4/13/2016 0:32:00",  7,           "red",                    "I do what I want.",           "Sandstorm",     "2/28",  "hilfinger",                                                                                                              "Image 1", 19                                 UNION
	SELECT "4/13/2016 1:07:09",  3,           "blue",                   "I'm a rebel",                 "Hello",         "12/25", "puppy",                                                                                                                  "Image 5", 100                                UNION
	SELECT "4/13/2016 1:23:36",  54,          "blue",                   "I do what I want.",           "Fur Elise",     "4/16",  "an h-dawg",                                                                                                              "Image 4", 97                                 UNION
	SELECT "4/13/2016 1:36:20",  14,          "navy blue",              "I'm a rebel",                 "Fur Elise",     "10/23", "sea otter",                                                                                                              "Image 4", 17                                 UNION
	SELECT "4/13/2016 1:44:21",  7,           "purple",                 "7",                           "Fur Elise",     "8/1",   "koala",                                                                                                                  "Image 1", 44                                 UNION
	SELECT "4/13/2016 2:26:35",  17,          "cs",                     "I do what I want.",           "Hello",         "1/17",  "cs is life",                                                                                                             "Image 3", 11                                 UNION
	SELECT "4/13/2016 2:55:47",  77,          "purple",                 "7",                           "Fur Elise",     "9/20",  "real",                                                                                                                   "Image 5", 18                                 UNION
	SELECT "4/13/2016 3:11:36",  99,          "red",                    "7",                           "Fur Elise",     "12/25", "greyhound",                                                                                                              "Image 1", 10                                 UNION
	SELECT "4/13/2016 3:51:47",  49,          "red",                    "7",                           "Sandstorm",     "12/22", "paul hilfinger",                                                                                                         "Image 4", 19                                 UNION
	SELECT "4/13/2016 9:01:13",  27,          "blue",                   "7",                           "Hello",         "5/13",  "pterosaur",                                                                                                              "Image 2", 14                                 UNION
	SELECT "4/13/2016 9:27:28",  7,           "red",                    "7",                           "Hello",         "3/12",  "golden retriever",                                                                                                       "Image 1", 86                                 UNION
	SELECT "4/13/2016 9:51:03",  7,           "mint",                   "I do what I want.",           "Trololol",      "10/2",  "unicorn",                                                                                                                "Image 3", 9                                  UNION
	SELECT "4/13/2016 10:19:41", 1,           "blue",                   "Choose this option instead.", "Sandstorm",     "1/1",   "chinchilla",                                                                                                             "Image 5", 59                                 UNION
	SELECT "4/13/2016 10:25:06", 42,          "blue",                   "7",                           "Fur Elise",     "4/11",  "phoenix",                                                                                                                "Image 2", 71                                 UNION
	SELECT "4/13/2016 10:28:27", 8,           "green",                  "Choose this option instead.", "Sandstorm",     "5/29",  "pygmy african hedgehog",                                                                                                 "Image 2", 11                                 UNION
	SELECT "4/13/2016 10:33:06", 45,          "blue",                   "7",                           "Hello",         "4/23",  "teacup pig",                                                                                                             "Image 5", 33                                 UNION
	SELECT "4/13/2016 10:59:45", 5,           "blue",                   "I do what I want.",           "Trololol",      "4/11",  "cat",                                                                                                                    "Image 5", 1                                  UNION
	SELECT "4/13/2016 11:02:23", 88,          "green",                  "I do what I want.",           "Hello",         "10/31", "cat",                                                                                                                    "Image 1", 1                                  UNION
	SELECT "4/13/2016 11:20:52", 7,           "blue",                   "YOLO!",                       "Hotline Bling", "1/1",   "stitch",                                                                                                                 "Image 2", 1                                  UNION
	SELECT "4/13/2016 11:30:43", 5,           "red",                    "7",                           "Hello",         "3/6",   "unicorn",                                                                                                                "Image 2", 512                                UNION
	SELECT "4/13/2016 11:59:15", 13,          "indigo",                 "I'm a rebel",                 "Fur Elise",     "1/1",   "pygmy puff (harry potter reference)",                                                                                    "Image 4", 4                                  UNION
	SELECT "4/13/2016 12:05:35", 24,          "blue!",                  "I do what I want.",           "Sandstorm",     "2/17",  "george w. bush",                                                                                                         "Image 4", 3                                  UNION
	SELECT "4/13/2016 12:14:38", 69,          "blue",                   "You are not the boss of me!", "Trololol",      "4/13",  "a clone of myself",                                                                                                      "Image 3", 88                                 UNION
	SELECT "4/13/2016 12:16:17", 8,           "blue",                   "7",                           "Sandstorm",     "11/10", "phoenix",                                                                                                                "Image 1", 23                                 UNION
	SELECT "4/13/2016 12:33:30", 7,           "pink",                   "Choose this option instead.", "Fur Elise",     "7/7",   "trex",                                                                                                                   "Image 1", 12                                 UNION
	SELECT "4/13/2016 12:44:08", 42,          "blue",                   "Choose this option instead.", "Sandstorm",     "6/22",  "lemur",                                                                                                                  "Image 5", 41                                 UNION
	SELECT "4/13/2016 12:56:09", 11,          "gray",                   "7",                           "Fur Elise",     "7/4",   "pikachu",                                                                                                                "Image 3", 11                                 UNION
	SELECT "4/13/2016 12:57:36", 55,          "black",                  "Choose this option instead.", "Work",          "6/15",  "dog",                                                                                                                    "Image 4", 73                                 UNION
	SELECT "4/13/2016 13:17:43", 69,          "blue",                   "YOLO!",                       "",              "7/4",   "snorlax",                                                                                                                "Image 4", 25                                 UNION
	SELECT "4/13/2016 13:23:10", 50,          "purple ",                "Choose this option instead.", "Hello",         "9/14",  "kitty",                                                                                                                  "Image 1", 9                                  UNION
	SELECT "4/13/2016 13:53:24", 21,          "21",                     "7",                           "Fur Elise",     "4/9",   "german shephard",                                                                                                        "Image 4", 1                                  UNION
	SELECT "4/13/2016 14:06:54", 17,          "blue",                   "7",                           "Hello",         "4/15",  "dragon",                                                                                                                 "Image 5", 1                                  UNION
	SELECT "4/13/2016 14:16:11", 1,           "red",                    "Choose this option instead.", "Sandstorm",     "",      "chupacabra ",                                                                                                            "Image 1", 16                                 UNION
	SELECT "4/13/2016 14:16:43", 1,           "blue",                   "I do what I want.",           "Hotline Bling", "4/1",   "a rock",                                                                                                                 "Image 1", 18                                 UNION
	SELECT "4/13/2016 15:32:59", 42,          "violet",                 "7",                           "Fur Elise",     "1/15",  "wolverine",                                                                                                              "Image 3", 54                                 UNION
	SELECT "4/13/2016 16:45:13", 2,           "yellow",                 "YOLO!",                       "Trololol",      "12/5",  "hilfinger",                                                                                                              "Image 1", 42                                 UNION
	SELECT "4/13/2016 17:57:54", 14,          "green",                  "7",                           "Hello",         "12/25", "griffin",                                                                                                                "Image 1", 14                                 UNION
	SELECT "4/13/2016 18:20:50", 18,          "red",                    "7",                           "Hello",         "2/18",  "little chihuaha",                                                                                                        "Image 4", 1                                  UNION
	SELECT "4/13/2016 18:24:04", 4,           "",                       "",                            "",              "",      "",                                                                                                                       "",        -1                                 UNION
	SELECT "4/13/2016 19:11:35", 7,           "black",                  "7",                           "Work",          "1/9",   "samoyed",                                                                                                                "Image 5", 100                                UNION
	SELECT "4/13/2016 19:24:57", 7,           "rainbow",                "7",                           "Hello",         "5/9",   "liger",                                                                                                                  "Image 2", 17                                 UNION
	SELECT "4/13/2016 20:39:55", 69,          "white",                  "Choose this option instead.", "",              "1/1",   "",                                                                                                                       "Image 2", 1                                  UNION
	SELECT "4/13/2016 22:55:42", 69,          "green",                  "YOLO!",                       "Sandstorm",     "12/25", "cerberus",                                                                                                               "Image 4", 27                                 UNION
	SELECT "4/14/2016 0:13:02",  37,          "no",                     "Choose this option instead.", "Fur Elise",     "4/12",  "dragon",                                                                                                                 "Image 1", 12                                 UNION
	SELECT "4/14/2016 0:13:04",  64,          "blue",                   "You are not the boss of me!", "Trololol",      "4/11",  "dragon",                                                                                                                 "Image 5", 8                                  UNION
	SELECT "4/14/2016 1:02:53",  69,          "dick",                   "Choose this option instead.", "Work",          "12/3",  "tiger",                                                                                                                  "Image 4", 9E+19                              UNION
	SELECT "4/14/2016 1:46:34",  50,          "blue",                   "I do what I want.",           "Fur Elise",     "8/13",  "puppy",                                                                                                                  "Image 3", 65                                 UNION
	SELECT "4/14/2016 2:04:52",  2,           "gold",                   "7",                           "Fur Elise",     "11/3",  "wolfdog",                                                                                                                "Image 4", 12                                 UNION
	SELECT "4/14/2016 3:05:12",  17,          "purple",                 "YOLO!",                       "Fur Elise",     "1/3",   "moehog",                                                                                                                 "Image 2", 39                                 UNION
	SELECT "4/14/2016 9:43:14",  71,          "burgundy ",              "I do what I want.",           "Sandstorm",     "10/31", "hedgehog ",                                                                                                              "Image 2", 14                                 UNION
	SELECT "4/14/2016 11:29:20", 69,          "black",                  "7",                           "Sandstorm",     "2/14",  "james uejio",                                                                                                            "Image 1", 17                                 UNION
	SELECT "4/14/2016 11:33:34", 2,           "black",                  "7",                           "Work",          "4/10",  "big fat kitty.",                                                                                                         "Image 1", 42                                 UNION
	SELECT "4/14/2016 12:47:13", 2,           "green",                  "7",                           "Fur Elise",     "4/23",  "monkey",                                                                                                                 "Image 5", 14                                 UNION
	SELECT "4/14/2016 13:42:42", 7,           "black",                  "7",                           "Fur Elise",     "8/12",  "ewok",                                                                                                                   "Image 1", 19                                 UNION
	SELECT "4/14/2016 13:49:20", 13,          "n/a",                    "7",                           "",              "9/5",   "",                                                                                                                       "Image 3", 1794                               UNION
	SELECT "4/14/2016 14:28:49", 42,          "navy blue ",             "Choose this option instead.", "Fur Elise",     "10/6",  "dragon ",                                                                                                                "Image 4", 1                                  UNION
	SELECT "4/14/2016 14:37:52", 4,           "light blue",             "7",                           "Sandstorm",     "2/29",  "dog",                                                                                                                    "Image 4", 1                                  UNION
	SELECT "4/14/2016 14:43:32", 12,          "brown",                  "I do what I want.",           "Hotline Bling", "2/29",  "john denero",                                                                                                            "Image 3", 1337                               UNION
	SELECT "4/14/2016 14:55:57", -1,          "",                       "",                            "",              "",      "",                                                                                                                       "",        1336                               UNION
	SELECT "4/14/2016 15:31:28", 3,           "green",                  "I do what I want.",           "Hotline Bling", "1/5",   "james uejio",                                                                                                            "Image 5", 6                                  UNION
	SELECT "4/14/2016 16:04:20", 69,          "blue",                   "I do what I want.",           "Trololol",      "4/20",  "paul hilfinger",                                                                                                         "Image 1", 333                                UNION
	SELECT "4/14/2016 16:52:26", 21,          "silver",                 "I do what I want.",           "Sandstorm",     "5/19",  "okapi",                                                                                                                  "Image 3", 73                                 UNION
	SELECT "4/14/2016 18:55:54", 25,          "yellow",                 "7",                           "Hotline Bling", "5/20",  "",                                                                                                                       "Image 3", 1                                  UNION
	SELECT "4/14/2016 19:02:18", 42,          "green",                  "7",                           "Hello",         "10/3",  "baymax",                                                                                                                 "Image 5", 4                                  UNION
	SELECT "4/15/2016 0:34:12",  21,          "green",                  "Choose this option instead.", "Hello",         "2/27",  "a house-elf",                                                                                                            "Image 2", 16                                 UNION
	SELECT "4/15/2016 0:40:14",  7,           "black",                  "7",                           "Sandstorm",     "1/1",   "puppy",                                                                                                                  "Image 4", 13                                 UNION
	SELECT "4/15/2016 8:48:22",  67,          "red..",                  "7",                           "Fur Elise",     "4/7",   "paul hilfinger",                                                                                                         "Image 4", 13                                 UNION
	SELECT "4/15/2016 9:33:15",  21,          "white",                  "7",                           "Hello",         "10/21", "pegasus",                                                                                                                "Image 5", 1                                  UNION
	SELECT "4/15/2016 10:11:43", 74,          "blue",                   "Choose this option instead.", "Fur Elise",     "12/25", "a penguin!",                                                                                                             "Image 2", 1                                  UNION
	SELECT "4/15/2016 10:19:58", 3,           "blue",                   "I do what I want.",           "Sandstorm",     "10/30", "",                                                                                                                       "Image 1", 3                                  UNION
	SELECT "4/15/2016 11:16:07", 8,           "blue",                   "7",                           "Hotline Bling", "1/31",  "shenron",                                                                                                                "Image 4", 14                                 UNION
	SELECT "4/15/2016 13:01:12", 69,          "black",                  "YOLO!",                       "Fur Elise",     "1/8",   "duck",                                                                                                                   "Image 4", 23                                 UNION
	SELECT "4/15/2016 15:17:32", 69,          "fafafafafafafa",         "YOLO!",                       "",              "2/29",  "a fufu",                                                                                                                 "Image 5", 1                                  UNION
	SELECT "4/15/2016 15:46:17", 3,           "black",                  "I do what I want.",           "Hello",         "3/29",  "panda",                                                                                                                  "Image 4", 29                                 UNION
	SELECT "4/15/2016 18:09:17", 89,          "black",                  "I'm a rebel",                 "",              "1/7",   "pig",                                                                                                                    "Image 3", 1                                  UNION
	SELECT "4/15/2016 19:12:49", 75,          "blue",                   "7",                           "Sandstorm",     "1/30",  "chia pet",                                                                                                               "Image 1", 12                                 UNION
	SELECT "4/15/2016 19:41:23", 99,          "dark red/wine red",      "7",                           "Hello",         "7/5",   "dragon",                                                                                                                 "Image 5", 6                                  UNION
	SELECT "4/15/2016 20:48:13", 31,          "blue",                   "Choose this option instead.", "Sandstorm",     "1/1",   "pikachu",                                                                                                                "Image 2", 18                                 UNION
	SELECT "4/15/2016 22:55:05", 19,          "pink",                   "7",                           "Hotline Bling", "10/17", "neopet",                                                                                                                 "Image 5", 45                                 UNION
	SELECT "4/16/2016 1:26:25",  1,           "",                       "I'm a rebel",                 "",              "",      "",                                                                                                                       "",        -1                                 UNION
	SELECT "4/16/2016 6:55:26",  61,          "yellow",                 "Choose this option instead.", "Sandstorm",     "1/9",   "beaver",                                                                                                                 "Image 4", 11;